<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="chethan" failures="2" tests="2" name="Rerun failed Tests" time="49.567" errors="0" timestamp="2025-08-03T11:58:42 IST">
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="29.034">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;com.aventstack.extentreports.ExtentTest.pass(String)&amp;quot; because &amp;quot;hooks.Hooks.test&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "com.aventstack.extentreports.ExtentTest.pass(String)" because "hooks.Hooks.test" is null
at hooks.Hooks.tearDown(Hooks.java:83)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="20.47">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;com.aventstack.extentreports.ExtentTest.pass(String)&amp;quot; because &amp;quot;hooks.Hooks.test&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "com.aventstack.extentreports.ExtentTest.pass(String)" because "hooks.Hooks.test" is null
at hooks.Hooks.tearDown(Hooks.java:83)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- Rerun failed Tests -->
